login: &login
  adapter: mysql
  username: root
  password: 
  host: localhost

development:
  <<: *login
  database: howwasyourday_dev

test:
  <<: *login
  database: howwasyourday_test

production:
  <<: *login
  database: howwasyourday_prod